backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/img"
public_folder: "/assets/img"
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "default"
      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/{{ title | slug | urlEscape }}/index.html"
      - label: "Title" 
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Components"
        name: "components"
        widget: "list"
        types:
          - label: "One Column Text"
            name: "oneColumnText"
            widget: "object"
            fields:
              - label: "Section Heading"
                name: "heading"
                widget: "string"
              - label: "Hide Heading"
                name: "hideHeading"
                widget: "boolean"
                required: false
                default: false
              - label: "Content"
                name: "content"
                widget: "markdown"
          - label: "Two Column Text"
            name: "twoColumnText"
            widget: "object"
            fields:
              - label: "Section Heading"
                name: "heading"
                widget: "string"
              - label: "Lead In"
                name: "leadin"
                widget: "markdown"
              - label: "Column 1"
                name: "columnOne"
                widget: "markdown"
              - label: "Column 2"
                name: "columnTwo"
                widget: "markdown" 
  - name: "posts"
    label: "Post"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/{{ title | slug | urlEscape }}/index.html"
      - label: "Title" 
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Share Image"
        name: "shareImage"
        required: false
        widget: "image"
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Author"
        name: "author"
        widget: "string"

