backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/img"
public_folder: "/assets/img"
collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{ slug }}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
